[database]
host = "localhost"
user = "your user"
password = "your password"
database = "your database"
port = 3306
[backup]
dump_dir = "your chosen directory to store dumps"
mysqldump_path = "Your path to /MySQL Server 8.4/bin/mysqldump.exe"
mysql_path = "Your path to /MySQL/MySQL Server 8.4/bin/mysql.exe"
config_path = "Path to .my.cnf"